"""
Configurations for AlexNet
"""

image_net_config = {
    "dataset":        "image_net",
    "input_channels": 3,
    "conv1_out":      96,
    "conv1_kernel":   11,
    "conv1_pooling":  True,
    "conv2_out":      256,
    "conv2_kernel":   5,
    "conv2_pooling":  True,
    "conv3_out":      384,
    "conv3_kernel":   3,
    "conv4_out":      384,
    "conv4_kernel":   3,
    "conv5_out":      256,
    "conv5_kernel":   3,
    "conv5_pooling":  True,
    "full1_out":      4096,
    "full2_out":      4096,
    "out_channels":   1000,
    "loc_resp_norm":  True,
    "pooling_kernel": 3,
    "pooling_stride": 2,
    "learning_rate":  1e-3,
    "batch_size":     128,
}

cifar10_config = {
    "dataset":        "cifar10",
    "input_channels": 3,
    "conv1_out":      48,
    "conv1_kernel":   3,
    "conv1_pooling":  False,
    "conv2_out":      128,
    "conv2_kernel":   3,
    "conv2_pooling":  False,
    "conv3_out":      192,
    "conv3_kernel":   3,
    "conv4_out":      192,
    "conv4_kernel":   3,
    "conv5_out":      128,
    "conv5_kernel":   3,
    "conv5_pooling":  False,
    "full1_out":      500,
    "full2_out":      500,
    "out_channels":   10,
    "loc_resp_norm":  True,
    "pooling_kernel": 3,
    "pooling_stride": 2,
    "learning_rate":  1e-3,
    "batch_size":     256,
}

cifar100_config = {
    "dataset":        "cifar100",
    "input_channels": 3,
    "conv1_out":      48,
    "conv1_kernel":   2,
    "conv1_pooling":  False,
    "conv2_out":      128,
    "conv2_kernel":   2,
    "conv2_pooling":  False,
    "conv3_out":      192,
    "conv3_kernel":   2,
    "conv4_out":      192,
    "conv4_kernel":   2,
    "conv5_out":      128,
    "conv5_kernel":   2,
    "conv5_pooling":  False,
    "full1_out":      500,
    "full2_out":      500,
    "out_channels":   100,
    "loc_resp_norm":  True,
    "pooling_kernel": 3,
    "pooling_stride": 2,
    "learning_rate":  1e-3,
    "batch_size":     128,
}